### PR TITLE
Version control

### PR DESCRIPTION
**Pull request by JonatanWang**
1. Configure .bumpversion.cfg;
2. Add VERSION, which is a text file containing current version number;
3. Semantic versioning: major-minor-patch;
4. Add new tag v1.3.0.

### CODE REVIEW

**Comment by HeMan** [comment]
Why have a separate file with version number in?

**Comment by HeMan** [comment]
Also, it seems like a good idea to change bumpversion to bump2version since bumpversion is currently unmaintained.

**Comment by JonatanWang** [comment]
It is bump2version installed for the project; we can simply run `cat VERSION` in shell to see version number, nothing else from the separate file with version number in.

**Comment by HeMan** [comment]
Please update requirements-dev.txt to use bump2version.

**Comment by JonatanWang** [comment]
Yes, requirements-dev.txt is updated just now.

**Pull request merged**
